# Generated by Django 4.2 on 2024-10-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insidencia', '0002_producto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('inicial', 'Inicial'), ('progreso', 'En progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
