# Generated by Django 4.2 on 2024-10-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insidencia', '0003_alter_producto_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada')], default='pendiente', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
