# Generated by Django 4.2 on 2024-10-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insidencia', '0004_insidencia_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='bancos_imagenes/')),
                ('status1', models.BooleanField(default=True)),
                ('status2', models.BooleanField(default=False)),
                ('custom1', models.CharField(blank=True, max_length=255, null=True)),
                ('custom2', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ventas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ganancias', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
