# Generated by Django 4.2 on 2024-10-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insidencia', '0005_banco_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='porcentaje_ganancias1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
